# Generated by Django 5.1.3 on 2025-04-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0002_testgroup_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='testgroup',
            name='created_by',
        ),
    ]
