# Generated by Django 5.1.3 on 2025-04-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0003_remove_test_created_by_remove_testgroup_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='testgroup',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
